"""add_history

Revision ID: adf4f3b980da
Revises: 
Create Date: 2026-08-14 16:28:18.083187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf4f3b980da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_medication_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_medication_id', sa.Uuid(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_medication_history')
    # ### end Alembic commands ###
